FROM nginx:latest

COPY docker/development/reverseProxy/ssl  /etc/nginx/ssl


COPY docker/development/reverseProxy/proxy.conf /etc/nginx/conf.d/proxy.conf
COPY docker/development/reverseProxy/nginx.conf /etc/nginx/nginx.conf

COPY docker/development/reverseProxy/reverseProxy.conf  /etc/nginx/conf.d/reverseProxy.conf

CMD ["nginx", "-g", "daemon off;"]
